### ISSUE TITLE
Light sources not applied within `<Coordinates>`

### ISSUE THREAD

**Issue by makeeno** [RodrigoHamuy/react-three-map#66]
We've noticed that every time we use `<Coordinates>` the meshes inside are black because the light source is not being applied: https://codesandbox.io/p/sandbox/react-three-map-basic-app-forked-jk3swn

Then I found https://github.com/RodrigoHamuy/react-three-map/issues/61#issuecomment-1746370543:

> Each `<Coordinates>` component is a new Three Scene [...]

which is probably the cause of this issue.

Background: We have a bunch of `features` we get from `map.querySourceFeatures` - each has its own coordinates and we thought we could just wrap `<Coordinates>` around each one.
The workaround is to also apply a light source for each one of them but I doubt that this can be considered good practice.

**Comment by RodrigoHamuy** [comment]
> The workaround is to also apply a light source for each one of them but I doubt that this can be considered good practice.

Hi @makeeno , that is indeed the only solution at the moment, because as you said, each coordinate is its own scene. Feel free to bring a different solution through PRs, but is not something that I myself will be changing [anytime soon](https://github.com/RodrigoHamuy/react-three-map/issues/61#issuecomment-1754666150), sorry 🙏 .

**Comment by forerunrun** [comment]
hey @makeeno you can use a slightly adjusted workflow wrapping objects in a `<group>` instead of `<coordinates>` and setting the groups position from co-ords to `vector3`... here's an example...

https://codesandbox.io/p/sandbox/react-three-map-basic-app-forked-h2w3vn?file=%2Fsrc%2FApp.tsx%3A43%2C24

the co-ords to vector3 function was provided by @RodrigoHamuy in another thread...
